### ISSUE TITLE
Possible to do a fuzzy-match LIKE query?

### ISSUE THREAD

**Issue by timburgan** [cipherstash/activestash#37]
Hello

With Rails 7's ActiveRecord encryption, including in deterministic mode, it's not possible to do fizzy match queries using SQLs `LIKE` operator.

Is this possible with ActiveStash?

If I have a User model like:

| id | name | email |
| -- | -- | -- |
| 1 | Jen O | jen@example.net |
| 2 | Timmay | timmay@example.org |
| 3 | Tim B | tim@example.com |

Without encrypted data, I want to do a query like the following:

```rb
# this will return 2 records
User.where('email LIKE ?', 'tim')
```

Using ActiveStash, is that what [this](https://github.com/cipherstash/activestash/blob/c508c702d6e1aba068856f1738d8d310c986c7dc/README.md?plain=1#L194) does, or is that doing something different?:

```rb
User.query { |q| q.email =~ 'tim' }
```

I assume it supports any regex pattern like the convention for that operator is in Ruby?

**Comment by freshtonic** [comment]
Hi @timburgan 

ActiveStash supports fuzzy string matching. It all comes down to how the indexing is configured in your model.

By default, using `stash_index` on a string field in your model, e.g. `stash_index :email`, will allow you to perform exact, range and match queries on that field. The index type "match" is what provides the fuzzy matching.

The text filtering and tokenisation that happens behind the scenes looks like this:

`"jen@example.net"`  -> `downcase` -> `tokenise` (split on whitespace and special chars) -> `ngram` (with token length of 3)

When saving the record for "jen@example.net" you'd end up with something like the following terms in the CipherStash index for the `email` field on your Users collection:

- jen
- exa
- xam
- amp
- mpl
- net

When querying, the same text tokenisation pipeline is applied to your query terms (i.e. the right hand side of the `~=` operator), and if any tokens generate from the query term match any of the tokens from the `email` index it will return the record.

Text tokenisation pipelines are not yet configurable in ActiveStash but that is on our roadmap.

All terms stored in the CipherStash index and terms produced by a query are of course encrypted and CipherStash cannot see them.

Note that matching using a regular expression is not supported. We take your point that (ab)using the `~=` operator make be misleading. I think that the least we can do is provide a sensible error message if someone tries to use it with a regular expression.

**Comment by timburgan** [comment]
🥇 love it, thank you @freshtonic
